# This is a basic workflow to help you get started with Actions

name: Docker CI
   
# Controls when the workflow will run
on:
  push:
    tags:     # Pattern matched against refs/tags
      - '*'   # Push events to every tag not containing /
#   push:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FOLDER: "."
  REGISTRY: ${{ secrets.DESCIL_REGISTRY_URL }}
  ORG: descil
  REPO: datascience
  LABEL: smartriqs
  NAMESPACE: descil

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: descil-runners
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4

    - name: Get latest tag pushed
      id: tag
      uses: 32teeth/action-github-tag@v1.0.7

    - name: Get latest version pushed
      id: version
      uses: 32teeth/action-github-tag@v1.0.7
      with:
        numbers_only: true

    - name: Return latest tag and version pushed
      run: echo ${{steps.tag.outputs.tag}} ${{steps.version.outputs.tag}}

    # Build Container
    - name: Login to GitLab
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DESCIL_REGISTRY_URL }}
        username: ${{ secrets.DESCIL_REGISTRY_USER }}
        password: ${{ secrets.DESCIL_REGISTRY_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build . --file $FOLDER/Dockerfile --tag $REGISTRY/$ORG/$REPO/$LABEL:${{steps.tag.outputs.tag}} --build-arg http_proxy="http://proxy.ethz.ch:3128" --build-arg https_proxy="http://proxy.ethz.ch:3128"

    - name: Push the Docker image
      run: docker push $REGISTRY/$ORG/$REPO/$LABEL:${{steps.tag.outputs.tag}}
    
    - name: Tag the Docker image
      run: docker tag $REGISTRY/$ORG/$REPO/$LABEL:${{steps.tag.outputs.tag}} $REGISTRY/$ORG/$REPO/$LABEL:latest
    
    - name: Push Docker tag
      run: docker push $REGISTRY/$ORG/$REPO/$LABEL:latest
