# This is a basic workflow to help you get started with Actions

name: Docker CI
   
# Controls when the workflow will run
on:
  push:
    tags:     # Pattern matched against refs/tags
      - '*'   # Push events to every tag not containing /
#   push:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FOLDER: "."
  REGISTRY: ${{ secrets.DESCIL_REGISTRY_URL }}
  ORG: descil
  REPO: datascience
  LABEL: smartriqs
  NAMESPACE: descil

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: descil-runners
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4

    # Build Container
    - name: Login to GitLab
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DESCIL_REGISTRY_URL }}
        username: ${{ secrets.DESCIL_REGISTRY_USER }}
        password: ${{ secrets.DESCIL_REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file $FOLDER/Dockerfile --tag $REGISTRY/$ORG/$REPO/$LABEL:latest --build-arg http_proxy="http://proxy.ethz.ch:3128" --build-arg https_proxy="http://proxy.ethz.ch:3128"
    
    - name: Push the Docker image
      run: docker push $REGISTRY/$ORG/$REPO/$LABEL:latest

    # Deploy on Kubernetes
    - uses: azure/setup-kubectl@v4
      id: install
    - uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_KUBECONFIG }}
    - name: Redeploy smartriqs
      run: kubectl rollout restart deployment descil-smartriqs -n $NAMESPACE
